
services:
  rplidar:
    image: rplidar:latest
    container_name: rplidar
    network_mode: host
    volumes:
      - /dev:/dev
    device_cgroup_rules:
      - 'c 188:* rmw'   
      - 'c 189:* rmw'   
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
               source /ros2_ws/install/setup.bash &&
               ros2 launch sllidar_ros2 sllidar_a1_launch.py serial_port:=/dev/rplidar serial_baudrate:=115200"
    environment:
      - ROS_DOMAIN_ID=42
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    stdin_open: true
    tty: true
    restart: unless-stopped
